# Site settings
title: Yomi
email: mohamed6aminbenchrifa@gmail.com
description: Yomi API is a free-to-use Japanese tokenizer and morphological analysis web API. It can take a Japanese text as an input and return a JSON response containing the tokenized text.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ookii-tsuki.github.io/yomi" # the base hostname & protocol for your site

# Build settings
markdown: GFM
plugins:
  - jekyll-feed

# Theme settings
theme: jekyll-theme-cayman
